test_0 (__main__.lab1a)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test for file creation: ./lab1a.py ... FAIL

======================================================================
FAIL: test_0 (__main__.lab1a)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test for file creation: ./lab1a.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ssharma608/ops445/lab1/./CheckLab1.py", line 60, in test_0
    self.assertTrue(os.path.exists('./lab1a.py'), msg=error_output)
AssertionError: False is not true : your file cannot be found(HINT: make sure you AND your file are in the correct directory)

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
OPS445 Lab Report - System Information for running ./CheckLab1.py
=================================================================
    User login name: ssharma608
    Git Email: shikshyasharma974@gmail.com
    Linux system name: ssharma-ops
    Python executable: /usr/bin/python3
    Python version:  3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
    OS Platform: linux
    Working Directory: /home/ssharma608/ops445/lab1
    Start at: Wed Jan 29 17:48:13 2025
=================================================================
